@playground_HostAddress = http://localhost:5083

GET {{playground_HostAddress}}/api/AuthTest/public
Accept: application/json

###

GET {{playground_HostAddress}}/api/AuthTest/protected
Accept: application/json

Authorization: Bearer <your-jwt-token>

###

GET {{playground_HostAddress}}/api/AuthTest/admin
Accept: application/json

Authorization: Bearer <your-jwt-token>

###
